### ISSUE TITLE
Miscellaneous crash when initializing Patapolis 

### ISSUE THREAD

**Issue by ArtainR** [OwocekTV/V4Hero#69]
When initializing Patapolis, or more specifically during the addition of 2nd and 6th layer textures, game crashes.
This does not appear to happen on Windows systems (or, more specifically, owocek's PC).

The crash messages I encountered:
```
Segmentation fault (core dumped)
```
```
double free or corruption (out)
Aborted (core dumped)
```
```
double free or corruption (fasttop)
Aborted (core dumped)
```

Screenshot:
![image](https://user-images.githubusercontent.com/52716201/123704378-e0d0aa00-d865-11eb-90a2-1092700edcdb.png)

Note: I fully accept this might be a problem with how I compiled the source code:
```
artain@artain-MS-7A68:/mnt/Workspace/Games/Patafour/V4Hero-master$ cmake .
(...)
artain@artain-MS-7A68:/mnt/Workspace/Games/Patafour/V4Hero-master$ make
(...)
artain@artain-MS-7A68:/mnt/Workspace/Games/Patafour/V4Hero-master$ ./V4Hero
```

Info:
![image](https://user-images.githubusercontent.com/52716201/123704710-3f962380-d866-11eb-8c47-4ccd6c443821.png)

**Comment by ArtainR** [comment]
After further testing (i.e. commenting out the addition of layer 2 and 6), this happens later in the initialization too, with other things.

More screenshots:
![image](https://user-images.githubusercontent.com/52716201/123828357-b2a0a800-d901-11eb-8b3e-3e278707faf4.png)
![image](https://user-images.githubusercontent.com/52716201/123828443-c5b37800-d901-11eb-8cae-a59828192da2.png)
![image](https://user-images.githubusercontent.com/52716201/123828545-e2e84680-d901-11eb-8acc-fca01eb4622b.png)

**Comment by giovanniberti** [comment]
I run patafour on Linux fine, are you 100% sure that the crashes happen when pushing sprites into the vector?

**Comment by ArtainR** [comment]
The screenshots are real, so yeah, I guess?

If You'd like me to screenshare the crashes on Discord, I can do that? Might be easier to discuss it that way

**Comment by giovanniberti** [comment]
Sorry, I didn't want to insinuate they weren't real :)

Yeah, streaming on Discord is totally fine! (I'm gggiova on the patafour server)

**Comment by ArtainR** [comment]
Issue happens when using Nouveau drivers with NVIDIA.

As a workaround, use a proprietary driver instead.
