### ISSUE TITLE
Linux Black Screen after New Game

### ISSUE THREAD

**Issue by jptrzy** [OwocekTV/V4Hero#85]
After successfully building Patafour with these command:
```
mkdir build
cd build
cmake ../
make
```
and setting up options I press New Game button and only thing that awaits me after was black screen with text in right left corner "V4Hero Client 1.2". 

In logs it looks that save was successfully created, but beside it I don't know what can I do; I hadn't get yet enough time to look into code.

| | My Specs |
| -- | -- |
| OS | Arch Linux x86_64 |
| CPU | Intel i5-7600K (4) @ 4.200GHz |
| GPU | NVIDIA GeForce GTX 1070 |

[V4Hero-1.2.log](https://github.com/OwocekTV/V4Hero/files/8523035/V4Hero-1.2.log)

**Comment by jptrzy** [comment]
Wow It was fast. I wasn't expecting this. Thank you for help.

**Comment by OwocekTV** [comment]
The issue has been resolved. Entering "New game" now correctly leads to a cutscene and then proceeds to a sample mission.
